=== AlberRC/XMLyDTD2/Apartado3/aeropuerto.dtd
<!ELEMENT aeropuerto (nombreAeropuerto, datosVuelo, fechaPanel)>

<!ELEMENT nombreAeropuerto (#PCDATA)>

<!ELEMENT datosVuelo (diario?, origen, destino, horaSalida, horaLlegada)>
<!ATTLIST datosVuelo 
codigo ID #REQUIRED
estado (C|E|R) "E">
<!ELEMENT diario EMPTY>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT destino (#PCDATA)>
<!ELEMENT horaSalida (#PCDATA)>
<!ELEMENT horaLlegada (#PCDATA)>

<!ELEMENT fechaPanel (#PCDATA)>

=== AlberRC/XMLyDTD2/Apartado3/aeropuerto.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: Alber Ruiz Clemente
Curso: DAW1
Fecha: 27-03-2025
Ejercicio: Aeropuerto
-->
<!DOCTYPE aeropuerto SYSTEM "aeropuerto.dtd">
<aeropuerto>
    <nombreAeropuerto/>
    <datosVuelo codigo="" estado="">
        <diario/>
        <origen/>
        <destino/>
        <horaSalida/>
        <horaLlegada/>
    </datosVuelo>
    <fechaPanel/>
</aeropuerto>
